# Generated by Django 4.0.5 on 2022-07-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.category'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='imoveis/covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='photo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rental.photo'),
        ),
    ]
