# Generated by Django 4.0.5 on 2022-07-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('rental', '0002_alter_imovel_category_alter_imovel_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='tags',
            field=models.ManyToManyField(blank=True, default='', to='tag.tag'),
        ),
    ]
