# Generated by Django 4.0.5 on 2022-06-23 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_imovel_category_alter_imovel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='imoveis/covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='photo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rental.photo'),
        ),
    ]
