# Generated by Django 4.0.5 on 2022-07-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_imovel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='category',
            field=models.CharField(choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa'), ('Terreno', 'Terreno'), ('Cobertura', 'Cobertura'), ('Desconhecido', 'Desconhecido')], default='Desconhecido', max_length=30),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
