# Generated by Django 4.0.5 on 2022-07-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_modelimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
