# Generated by Django 4.0.5 on 2022-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_remove_imovel_photo_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='pics',
            field=models.FileField(blank=True, default='', upload_to='imoveis/pics/%Y/%m/%d/'),
        ),
    ]
