# Generated by Django 4.0.5 on 2022-07-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_imovel_pics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(blank='', default='', upload_to='imoveis/pics/%Y/%m/%d/')),
                ('pic2', models.ImageField(blank='', default='', upload_to='imoveis/pics/%Y/%m/%d/')),
                ('pic3', models.ImageField(blank='', default='', upload_to='imoveis/pics/%Y/%m/%d/')),
                ('pic4', models.ImageField(blank='', default='', upload_to='imoveis/pics/%Y/%m/%d/')),
                ('pic5', models.ImageField(blank='', default='', upload_to='imoveis/pics/%Y/%m/%d/')),
                ('pic6', models.ImageField(blank='', default='', upload_to='imoveis/pics/%Y/%m/%d/')),
                ('pic7', models.ImageField(blank='', default='', upload_to='imoveis/pics/%Y/%m/%d/')),
                ('pic8', models.ImageField(blank='', default='', upload_to='imoveis/pics/%Y/%m/%d/')),
                ('pic9', models.ImageField(blank='', default='', upload_to='imoveis/pics/%Y/%m/%d/')),
                ('pic10', models.ImageField(blank='', default='', upload_to='imoveis/pics/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelImage',
        ),
        migrations.AlterField(
            model_name='imovel',
            name='pics',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='rental.album'),
        ),
    ]
