# Generated by Django 4.0.5 on 2022-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_album_delete_modelimage_alter_imovel_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='pics',
        ),
        migrations.AddField(
            model_name='imovel',
            name='fifphoto',
            field=models.ImageField(blank=True, default='', upload_to='imoveis/photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='fourthphoto',
            field=models.ImageField(blank=True, default='', upload_to='imoveis/photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='mainphoto',
            field=models.ImageField(blank=True, default='', upload_to='imoveis/photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='secondphoto',
            field=models.ImageField(blank=True, default='', upload_to='imoveis/photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='sevphoto',
            field=models.ImageField(blank=True, default='', upload_to='imoveis/photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='sixphoto',
            field=models.ImageField(blank=True, default='', upload_to='imoveis/photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='thirdphoto',
            field=models.ImageField(blank=True, default='', upload_to='imoveis/photos/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
